### PR TITLE
feat(dart): Add a new Feature `dart`

### PR DESCRIPTION
**Pull request by eitsupi**
Continued from #23

### CODE REVIEW

**Comment by eitsupi** [comment]
I think it is fine functionally, but I would like to wait for #27 to be merged since Linter is not set up.

**Review by jcbhmr — APPROVED** [review]
Looks awesome! 👍 ❤️

**Comment by eitsupi** [comment]
@jcbhmr Have you read my comment?
My intention was merging #27 first and fix this PR by linters.

**Comment by jcbhmr** [comment]
My bad! 🤦‍♂️😬 Now I understand what you meant by that. Sorry about me jumping the shark! I'll try to leave merging PRs that _you author_ to _you_ and not do it prematurely. 😞

**Comment by eitsupi** [comment]
I apologize for my lack of comments. I should have left this as drafted.

I'm sorry, but could you please make the corrections immediately so that it will pass the linter? I don't have time to do it for a while.

**Comment by jcbhmr** [comment]
Will do!

**Comment by jcbhmr** [comment]
#28

**Pull request merged**
