### PR TITLE
docs: improve readme

### LINKED ISSUE #6: Improve readme

### PR DESCRIPTION
**Pull request by jcbhmr**
closes #6 

This doesn't remove the under construction banner (since we don't have anything to show for this repo yet), but it does add some badly needed _content_ to the readme!

### CODE REVIEW

**Comment by eitsupi** [comment]
We should merge #23 first.

**Review by eitsupi — CHANGES_REQUESTED** [review]
Thanks for updates.
Could you fix points the linter pointed out?

**Comment by jcbhmr** [comment]
Yep! I won't make the mistake of ignoring the linter again 😆

**Comment by jcbhmr** [comment]
This PR is currently BLOCKED by the website link being a 404. This PR should not be merged until the website exists.

**Comment by jcbhmr** [comment]
I've added some MarkdownLint disable comments:
```html
<!-- markdownlint-disable MD041 MD033 -->
```

Why?
- MD041: allow image to be first; the rule requires the first line be `# Heading`
- MD033: allow inline HTML for centered image; the rule disallows HTML

**Comment by eitsupi** [comment]
> * MD033: allow inline HTML for centered image; the rule disallows HTML

Note that only certain tags can be allowed.
https://github.com/rocker-org/rocker-versioned2/blob/30f354ba627c0148581426abd588b1e770802570/.markdownlint.yaml#L12-L13

**Comment by eitsupi** [comment]
@jcbhmr Could you take a look at this?

**Review by eitsupi — CHANGES_REQUESTED** [review]
Would you like to review the Linter settings as I commented above?

**Comment by eitsupi** [comment]
@jcbhmr Do you still plan to work on this project?

**Pull request closed without merging**
