### PR TITLE
Add tooling utils

### PR DESCRIPTION
**Pull request by jcbhmr**
This PR would...
- [x] Make it so that there's a prebuild script that copies util into each src folder
- [ ] Run prebuild in the github actions prior to publication and testing
- [x] make a wrapper test.sh script that runs prebuild, then delegates to `devcontainer features test`
- [x] add some util scripts for cmake and llvm (see below)

if the proposal to make shared stuff is already here, then this is redundant! yay! 🥳
https://github.com/devcontainers/spec/pull/209

it just needs to be implemented in the cli... until then, we're stuck doing the `cp utils src/$ID/utils` manually 🤷‍♀️

### CODE REVIEW

**Comment by eitsupi** [comment]
Is there any reason why we can't wait for devcontainers/spec#209 to be implemented in the CLI?

**Comment by jcbhmr** [comment]
> Is there any reason why we can't wait for [devcontainers/spec#209](https://github.com/devcontainers/spec/pull/209) to be implemented in the CLI?

no reason whatsoever! if we can wait until then, that's less work for me 👍

**Comment by eitsupi** [comment]
I do not think it is worthwhile to deviate from the standard workflow to implement this.

**Comment by jcbhmr** [comment]
sounds like a plan! 🚀 should i just copy the two script into the src/id/utils folder manually for now then? 🤔

```sh
# shellcheck shell=bash

clear_local_apt_index() (
  set -e
  
  rm -rf /var/lib/apt/lists/*
  echo '🟩 Cleared local apt index'
)

```

```sh
# shellcheck shell=bash

ensure_apt_packages() (
  set -e

  export DEBIAN_FRONTEND=noninteractive
  if dpkg -s "$@" &>/dev/null; then
    echo "🟦 $@ is already installed"
  else
    if [[ $(find /var/lib/apt/lists/* | wc -l) == 0 ]]; then
      echo '🟪 Updating local apt index...'
      apt-get update -y
      echo '🟩 Updated local apt index'
    fi
    echo "🟪 Installing $@..."
    apt-get install -y --no-install-recommends "$@"
    echo "🟩 Installed $@"
  fi
)

```

**Comment by eitsupi** [comment]
I think manual copying is best at this time.

I would prefer not to split scripts for functions of that length.
Without splitting, it would be very easy to simply copy the script and run it.

**Pull request closed without merging**
